name: "✨ Feature"
description: "새로운 기능 추가용 템플릿입니다."
labels: ["feature"]
  - type: textarea
    attributes:
      label: 📄 설명
    description: |
      📝 제목 작성 예시:
      ```
      [FEATURE] 사용자 로그인 기능 추가
      [BUG] 로그인 실패 시 에러 발생
      ```
      제목은 위 형식을 참고해서 작성해 주세요!
      placeholder: 자세히 적을수록 좋습니다.
    validations:
      required: true

- type: textarea
  attributes:
    label: ✅ 작업할 내용
    description: 할 일을 체크박스 형태로 작성해주세요.
    value: |
      - [ ] 작업 내용
      - [ ] 작업 내용
      - [ ] 작업 내용
      - [ ] 작업 내용
    render: markdown
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.
