name: Java CI with Gradle

on:
  pull_request:
    branches: [ "dev", "main" ]  # dev, main 모두 PR 대상

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: clean build